### Create insumo

POST http://localhost:8080/api/insumos/create HTTP/1.1
Content-Type: application/json

{
    "descricao": "teste",
    "valorUntMed": 0,
    "valorUntMedAuto": false,
    "undEstoque": "LITRO",
    "estoqueMinimo": 100,
    "idCategoria": 1
}

### Get insumos

GET http://localhost:8080/api/insumos/autocomplete?label=&page=0&size=10 HTTP/1.1

### Get insumo

GET http://localhost:8080/api/insumos/show/2 HTTP/1.1

### Create requisicao

POST http://localhost:8080/api/requisicoes-estoque/create HTTP/1.1
Content-Type: application/json

{
  "dataRequisicao": "2024-06-27T22:43:49.753Z",
  "obs": "",
  "ordemProducao":  "",
  "idRequisitante": 1,
  "idEquipamento": 1,
  "itens": [
    {
      "idItem": 1,
      "quantEntregue": 5,
      "idInsumo": 1,
      "undConsumo": "LITRO"
    }
  ]
}

### Get estimativa

GET http://localhost:8080/api/estoque/estimativa-duracao HTTP/1.1
