export const unidades = [
  { value: 'AMPOLA', label: 'AMPOLA' },
  { value: 'BALDE', label: 'BALDE' },
  { value: 'BANDEJ', label: 'BANDEJA' },
  { value: 'BARRA', label: 'BARRA' },
  { value: 'BISNAG', label: 'BISNAGA' },
  { value: 'BLOCO', label: 'BLOCO' },
  { value: 'BOBINA', label: 'BOBINA' },
  { value: 'BOMB', label: 'BOMBONA' },
  { value: 'CAPS', label: 'CAPSULA' },
  { value: 'CART', label: 'CARTELA' },
  { value: 'CENTO', label: 'CENTO' },
  { value: 'CJ', label: 'CONJUNTO' },
  { value: 'CM', label: 'CENTIMETRO' },
  { value: 'CM2', label: 'CENTIMETRO QUADRADO' },
  { value: 'CX', label: 'CAIXA' },
  { value: 'CX2', label: 'CAIXA COM 2 UNIDADES' },
  { value: 'CX3', label: 'CAIXA COM 3 UNIDADES' },
  { value: 'CX5', label: 'CAIXA COM 5 UNIDADES' },
  { value: 'CX10', label: 'CAIXA COM 10 UNIDADES' },
  { value: 'CX15', label: 'CAIXA COM 15 UNIDADES' },
  { value: 'CX20', label: 'CAIXA COM 20 UNIDADES' },
  { value: 'CX25', label: 'CAIXA COM 25 UNIDADES' },
  { value: 'CX50', label: 'CAIXA COM 50 UNIDADES' },
  { value: 'CX100', label: 'CAIXA COM 100 UNIDADES' },
  { value: 'DISP', label: 'DISPLAY' },
  { value: 'DUZIA', label: 'DUZIA' },
  { value: 'EMBAL', label: 'EMBALAGEM' },
  { value: 'FARDO', label: 'FARDO' },
  { value: 'FOLHA', label: 'FOLHA' },
  { value: 'FRASCO', label: 'FRASCO' },
  { value: 'GALAO', label: 'GALÃO' },
  { value: 'GF', label: 'GARRAFA' },
  { value: 'GRAMAS', label: 'GRAMAS' },
  { value: 'JOGO', label: 'JOGO' },
  { value: 'KG', label: 'QUILOGRAMA' },
  { value: 'KIT', label: 'KIT' },
  { value: 'LATA', label: 'LATA' },
  { value: 'LITRO', label: 'LITRO' },
  { value: 'M', label: 'METRO' },
  { value: 'M2', label: 'METRO QUADRADO' },
  { value: 'M3', label: 'METRO CÚBICO' },
  { value: 'MILHEI', label: 'MILHEIRO' },
  { value: 'ML', label: 'MILILITRO' },
  { value: 'MWH', label: 'MEGAWATT HORA' },
  { value: 'PACOTE', label: 'PACOTE' },
  { value: 'PALETE', label: 'PALETE' },
  { value: 'PARES', label: 'PARES' },
  { value: 'PC', label: 'PEÇA' },
  { value: 'POTE', label: 'POTE' },
  { value: 'K', label: 'QUILATE' },
  { value: 'RESMA', label: 'RESMA' },
  { value: 'ROLO', label: 'ROLO' },
  { value: 'SACO', label: 'SACO' },
  { value: 'SACOLA', label: 'SACOLA' },
  { value: 'TAMBOR', label: 'TAMBOR' },
  { value: 'TANQUE', label: 'TANQUE' },
  { value: 'TON', label: 'TONELADA' },
  { value: 'TUBO', label: 'TUBO' },
  { value: 'UNID', label: 'UNIDADE' },
  { value: 'VASIL', label: 'VASILHAME' },
  { value: 'VIDRO', label: 'VIDRO' }
] as const

export const tipo = [
  { value: 'ENTRADA', label: 'A Pagar' },
  { value: 'SAIDA', label: 'A Receber' }
] as const

export const situacao = [
  { value: 'EM_ABERTO', label: 'EM ABERTO' },
  { value: 'BAIXADO', label: 'BAIXADO' },
  { value: 'BAIXADO_PARCIALMENTE', label: 'BAIXADO PARCIALMENTE' }
] as const
