CREATE TABLE categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   nome VARCHAR(255) NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_categorias PRIMARY KEY (id)
);
ALTER TABLE categorias ADD CONSTRAINT uc_categorias_nome UNIQUE (nome);

CREATE TABLE insumos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   descricao VARCHAR(255) NOT NULL,
   valor_unt_med DECIMAL NOT NULL,
   valor_unt_med_auto BOOLEAN NOT NULL,
   und_estoque VARCHAR(255) NOT NULL,
   estoque_minimo DECIMAL NOT NULL,
   total_entradas DECIMAL NOT NULL,
   total_saidas DECIMAL NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   categorias_id BIGINT NOT NULL,
   CONSTRAINT pk_insumos PRIMARY KEY (id)
);
ALTER TABLE insumos ADD CONSTRAINT uc_insumos_descricao UNIQUE (descricao);
ALTER TABLE insumos ADD CONSTRAINT FK_INSUMOS_ON_CATEGORIAS FOREIGN KEY (categorias_id) REFERENCES categorias (id);

CREATE TABLE equipamentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   nome VARCHAR(255) NOT NULL,
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_equipamentos PRIMARY KEY (id)
);
ALTER TABLE equipamentos ADD CONSTRAINT uc_equipamentos_nome UNIQUE (nome);

CREATE TABLE requisitantes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   nome VARCHAR(255) NOT NULL,
   fone VARCHAR(255),
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_requisitantes PRIMARY KEY (id)
);
ALTER TABLE requisitantes ADD CONSTRAINT uc_requisitantes_nome UNIQUE (nome);

CREATE TABLE requisicoes_estoque (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   data_requisicao TIMESTAMP WITHOUT TIME ZONE,
   valor_total DECIMAL,
   ordem_producao VARCHAR(255),
   obs VARCHAR(255),
   created_at TIMESTAMP WITHOUT TIME ZONE,
   updated_at TIMESTAMP WITHOUT TIME ZONE,
   requisitantes_id BIGINT,
   equipamentos_id BIGINT,
   CONSTRAINT pk_requisicoes_estoque PRIMARY KEY (id)
);
ALTER TABLE requisicoes_estoque ADD CONSTRAINT FK_REQUISICOES_ESTOQUE_ON_EQUIPAMENTOS FOREIGN KEY (equipamentos_id) REFERENCES equipamentos (id);
ALTER TABLE requisicoes_estoque ADD CONSTRAINT FK_REQUISICOES_ESTOQUE_ON_REQUISITANTES FOREIGN KEY (requisitantes_id) REFERENCES requisitantes (id);

CREATE TABLE requisicoes_estoque_itens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   insumos_id BIGINT NOT NULL,
   quantidade DECIMAL NOT NULL,
   unidade VARCHAR(255) NOT NULL,
   valor_unitario DECIMAL NOT NULL,
   requisicoes_estoque_id BIGINT NOT NULL,
   CONSTRAINT pk_requisicoes_estoque_itens PRIMARY KEY (id)
);
ALTER TABLE requisicoes_estoque_itens ADD CONSTRAINT FK_REQUISICOES_ESTOQUE_ITENS_ON_INSUMOS FOREIGN KEY (insumos_id) REFERENCES insumos (id);
ALTER TABLE requisicoes_estoque_itens ADD CONSTRAINT FK_REQUISICOES_ESTOQUE_ITENS_ON_REQUISICOES_ESTOQUE FOREIGN KEY (requisicoes_estoque_id) REFERENCES requisicoes_estoque (id);