spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:printerp-dev}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:1943}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
